name: Deploy to GitHub Pages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install parcel --save-dev
      - run: npx parcel build src/index.html --dist-dir public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
